config/routes.rb
''# == Route Map
#
#        Prefix Verb   URI Pattern                 Controller#Action
# alapps_export GET    /alapps/export(.:format)    alapps#export
#        maapps GET    /maapps(.:format)           maapps#index
#               POST   /maapps(.:format)           maapps#create
#     new_maapp GET    /maapps/new(.:format)       maapps#new
#    edit_maapp GET    /maapps/:id/edit(.:format)  maapps#edit
#         maapp GET    /maapps/:id(.:format)       maapps#show
#               PATCH  /maapps/:id(.:format)       maapps#update
#               PUT    /maapps/:id(.:format)       maapps#update
#               DELETE /maapps/:id(.:format)       maapps#destroy
#       cbpapps GET    /cbpapps(.:format)          cbpapps#index
#               POST   /cbpapps(.:format)          cbpapps#create
#    new_cbpapp GET    /cbpapps/new(.:format)      cbpapps#new
#   edit_cbpapp GET    /cbpapps/:id/edit(.:format) cbpapps#edit
#        cbpapp GET    /cbpapps/:id(.:format)      cbpapps#show
#               PATCH  /cbpapps/:id(.:format)      cbpapps#update
#               PUT    /cbpapps/:id(.:format)      cbpapps#update
#               DELETE /cbpapps/:id(.:format)      cbpapps#destroy
#        alapps GET    /alapps(.:format)           alapps#index
#               POST   /alapps(.:format)           alapps#create
#     new_alapp GET    /alapps/new(.:format)       alapps#new
#    edit_alapp GET    /alapps/:id/edit(.:format)  alapps#edit
#         alapp GET    /alapps/:id(.:format)       alapps#show
#               PATCH  /alapps/:id(.:format)       alapps#update
#               PUT    /alapps/:id(.:format)       alapps#update
#               DELETE /alapps/:id(.:format)       alapps#destroy
#        ulapps GET    /ulapps(.:format)           ulapps#index
#               POST   /ulapps(.:format)           ulapps#create
#     new_ulapp GET    /ulapps/new(.:format)       ulapps#new
#    edit_ulapp GET    /ulapps/:id/edit(.:format)  ulapps#edit
#         ulapp GET    /ulapps/:id(.:format)       ulapps#show
#               PATCH  /ulapps/:id(.:format)       ulapps#update
#               PUT    /ulapps/:id(.:format)       ulapps#update
#               DELETE /ulapps/:id(.:format)       ulapps#destroy
#          root GET    /                           maapps#new
#

Rails.application.routes.draw do

  get 'main/index'
  get 'cbpapps/export', to: 'cbpapps#export'
  get 'ulapps/export', to: 'ulapps#export'
  get 'alapps/export', to: 'alapps#export'
  get 'maapps/export', to:  'maapps#export'

  get 'ulapps/successful', to: 'ulapps#successful'
  get 'cbpapps/successful', to: 'cbpapps#successful'
  get 'maapps/successful', to: 'maapps#successful'
  get 'alapps/successful', to: 'alapps#successful'

  resources :maapps

  resources :cbpapps

  resources :alapps

  resources :ulapps

  root 'main#index'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # http_basic_authenticate_with :name => MainHelper.name, :password => MainHelper.password, only: :index

  def index
    reset_session
  end
end

app/helpers/main_helper.rb
module MainHelper
  @name = "admin"
  @password = "password"

  def self.name
    @name
  end

  def self.password
    @password
  end

end

app/views/main/index.html.haml
%title Student Federal Credit Union
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    #header-navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "https://www.upennsfcu.org/about-us/"} About Us
        %li
          %a{:href => "https://www.upennsfcu.org/loans/"} Loans
        %li
          %a{:href => "https://www.upennsfcu.org/accounts/"} Accounts
        %li
          %a{:href => "https://www.upennsfcu.org/services/"} Services
        %li
          %a{:href => "https://www.upennsfcu.org/careers/"} Careers
        %li
          %a{:href => "https://www.upennsfcu.org/weekly-economic-review/"} Economic Review
        %li
          %a{:href => "https://www.upennsfcu.org/forms/"} Form Downloads
      .nav.navbar-nav.navbar-right
        .btn-group
          %button.btn.btn-primary.navbar-btn.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
            Apply Now!
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              = link_to 'Member Account Application', new_maapp_path
            %li
              = link_to 'Unsecured Loan Application', new_ulapp_path
            %li
              = link_to 'Auto Loan Application', new_alapp_path
            %li
              = link_to 'Credit Builder Program Application', new_cbpapp_path
        .btn-group
          %button.btn.btn-primary.navbar-btn.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
            Management
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              = link_to 'Member Account Management', maapps_path
            %li
              = link_to 'Unsecured Loan Management', ulapps_path
            %li
              = link_to 'Auto Loan Management', alapps_path
            %li
              = link_to 'Credit Builder Program Management', cbpapps_path
.row
  .col-xs-8
    .row
      .col-xs-6
        .panel.panel-default
          .panel-heading
            %h3.panel-title.text-center Credit Builder Program
          .panel-body
            %img.pull-left{:height => "100", :src => "/img/creditbuilder.jpg", :width => "100"}
              %h5
                Better credit without any risk or hassle.
                %br
                  %small SFCU's Credit Builder Loan is an easy way to establish or improve your credit score.
      .col-xs-6
        .panel.panel-default
          .panel-heading
            %h3.panel-title.text-center Free and unlimited incoming wires!
          .panel-body
            %img.pull-left{:height => "100", :src => "/img/dollarsign.png", :width => "100"}
              %h5
                Don't pay to receive
                %em your
                money.
                %br
                  %small Unlike at many other banks, SFCU members enjoy free and unlimited incoming wire transfers.
    .row
      .col-xs-12
        .panel.panel-default
          .panel-heading
            %h3.panel-title.text-center Questions / Concerns? Contact Us!
          .panel-body
            .row
              .col-xs-6
                %address.text-center
                  %strong SFCU Main Branch Office
                  %br
                    3401 Walnut St, Suite 431A
                    %br
                      Philadelphia, PA 19104
                      %br
                        %em Monday - Friday: 10am - 6pm
              .col-xs-6
                %dl.dl-horizontal
                  %dt Member Services
                  %dd (215) 222-2604
                  %dt Member Services (Fax)
                  %dd (215) 222-2607
                  %dt Lost/Stolen Debit Card
                  %dd (800) 523-4175
                  %dt General Email Inquiries
                  %dd
                    %a{:href => "mailto:support@upennsfcu.org"} Click here
            .row
              .col-xs-12
                %p.text-center
                  %strong Routing #
                  036-089-053
                  %small
                    (For incoming wires, click
                    = succeed ")" do
                      %a{:href => "https://www.upennsfcu.org/services/wire-transfers/"} here
            .row
              .col-xs-12
                %p.text-center
                  %small
                    %em For account security, please make all account-specific inquiries via Online Banking.
  .col-xs-4
    #ATMLocatorPanel.panel.panel-default
      .panel-heading
        %h3.panel-title.text-center ATM Locator
      .panel-body
        %img{:src => "/img/usamap.jpg"}
          %p.lead 55,000 surcharge-free ATMs. Worldwide.
          %form.form-inline{:action => "http://locator.allpointnetwork.com/SearchResults.aspx", :method => "post", :role => "form", :target => "_blank"}
            .form-group
              %label.sr-only{:for => "ZipCode"} ZIP Code
              .input-group.input-group-sm
                %span.input-group-addon
                  %span.glyphicon.glyphicon-search
                %input#ZipCode.form-control{:maxlength => "7", :name => "zipcode", :placeholder => "ZIP Code", :tabindex => "2", :type => "text"}
                  %span.input-group-btn
                    %button.btn.btn-default.btn-sm{:type => "submit"} Search
          %br
          .row
            .col-xs-6
              %dl
                %dt Campus ATMs
                %dd
                  %a{:href => "https://www.upennsfcu.org/services/atms/"} Campus ATMs
                %dd
                  %a{:href => "https://www.upennsfcu.org/services/penncard/"} PennCard ATMs
            .col-xs-6
              %dl
                %dt Worldwide ATMs
                %dd
                  %a{:href => "http://www.allpointnetwork.com/"} Allpoint Network

#externalURLWarningModal.modal.fade{:role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title External URL Warning
      .modal-body
        %p You are being redirected to an external website that is not controlled by the Student Federal Credit Union. We do not endorse and are not responsible for the content of this website.
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Go back
        %a#externalURLContinue.btn.btn-primary{:href => "#", :role => "button"} Continue to external website

:javascript
  $(document).ready(function() {
    $('#externalURLContinue').click(function(e) {
      $('#externalURLWarningModal').modal('hide');
    });

    $('a.external-link').click(function(e) {
      e.preventDefault();

      $('#externalURLContinue').attr('href', $(this).attr('href'));
      $('#externalURLContinue').attr('target', $(this).attr('target'));

      $('#externalURLWarningModal').modal();
    });
  });